[package]
name = "sokoban"
version = "0.1.0"
authors = ["mayeul"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
enum-map = "*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]